[toolchain]
anchor_version = "0.30.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
mango_farm = "2mLwsLjyi1qWR9KQrsRQERKB3PJbw6tnd1gcVtBwy85A"

[programs.devnet]
mango_farm = "2mLwsLjyi1qWR9KQrsRQERKB3PJbw6tnd1gcVtBwy85A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com "
wallet = "/home/studio-lab-user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "ts-node ./scripts/index.ts"